= gpssnmp(1)
:date: 13 July 2022
:keywords: gps, gpsd, gpssnmp
:manmanual: GPSD Documentation
:mansource: GPSD Version {gpsdver}
:robots: index,follow
:sectlinks:
:toc: macro
:type: manpage
:webfonts!:

include::../www/inc-menu.adoc[]

== NAME

gpssnmp - SNMP helper client for gpsd

== SYNOPSIS

*gpssnmp* [OPTIONS] [server[:port[:device]]]

*gpssnmp* -h

*gpssnmp* -g OID

*gpssnmp* -n OID

*gpssnmp* -V

== DESCRIPTION

*gpssnmp* is a *gpsd* client that works as an SNMP helper for *MRTG*.

*gpssnmp* does not require root privileges. It will also run fine as root.

The output of *gpssnmp* conforms to the requierments of the "pass [-p
priority] MIBOID PROG" option in *snmpd.conf*.  So it can be used to
extend *snmpd* with the *GPSD-MIB*.

== OPTIONS

*-?*, *-h*, *--help*::
  Print a summary of options and then exit.
*-g OID*::
  Get the specified OID.
*-n OID*::
  Get the next OID starting at OID.
*-V*, *--version*::
  Print the package version and exit.

Supported OID values are:
* .1.3.6.1.4.1.59054.11.2.1.3.1;; Number of sats seen.
* .1.3.6.1.4.1.59054.11.2.1.4.1;; Number of sats in use.
* .1.3.6.1.4.1.59054.11.2.1.5.1;; Average SNR of all used satellites. Times 10.

== EXAMPLES:

To get the number of saltellits seen with the OID

----
   $ gpssnmp -g .1.3.6.1.4.1.59054.11.2.1.3.1
   .1.3.6.1.4.1.59054.11.2.1.3.1
   INTEGER
   15
----

To get the number of saltellits seen with the MIB name

----
   $ gpssnmp -g skynSat.1
   .1.3.6.1.4.1.59054.11.2.1.3.1
   INTEGER
   15
----

=== Connecting to snmpd

*gpssnmp* can work as a "pass-through script" with *snmpd*.  To enable
this functionality on an already working snmpd installation, add this to your
*/etc/snmp/snmpd.conf* file, and then restart *snmpd*:

````
# be sure SNMPv2 community "public" can access all MIBs:
rocommunity public  localhost

# configure pass-thur of GPSD-MIB to gpssnmp
pass .1.3.6.1.4.1.59054  /usr/local/bin/gpssnmp
----

You can then query the number of satlettites in use this way:

````
$ snmpget -c public -v 2c localhost skynSat.1
GPSD-MIB::skynSat.1 = INTEGER: 16
````

Or dump the entire "sky" OID this way:

----
$ snmpwalk -c public -v 2c localhost GPSD-MIB::sky
GPSD-MIB::skynSat.1 = INTEGER: 17
GPSD-MIB::skyuSat.1 = INTEGER: 8
GPSD-MIB::skySNRavg.1 = INTEGER: 2000
----

== RETURN VALUES

*0*:: on success.
*1*:: on failure

== SEE ALSO

*cgps*(1), *gps*(1), *gpspipe*(1), *snmpget*(1), xgps*(1), snmpd.conf(5)  

*gpsd*(8)

== RESOURCES

*Project web site:* {gpsdweb}

== COPYING

This file is Copyright 2013 by the GPSD project +
SPDX-License-Identifier: BSD-2-clause
