#! /bin/sh

if (( $UID != 0 )); then
    echo "Please run as root"
fi

# print what we do
set -x
id
uname -a
cat /etc/*release
which gpsd
gpsd -V
# use netstat or ss, depending
if [ `which netstat` ]; then
    # FreeBSD does not support "-n"
    netstat -lp | egrep "gpsd|:2947"
elif [ `which ss` ]; then
    ss -lpn | egrep 'gpsd|:2947 '
fi
ps ax | fgrep gpsd
which gpspipe
gpspipe -V
gpspipe -w -n 2
echo PYTHONPATH $PYTHONPATH
head -n 1 `which xgps`
if [ `which python` ]; then
    python -V
    python -c "import gps;print(gps.__version__)"
fi
if [ `which python3` ]; then
    python3 -V
    python3 -c "import gps;print(gps.__version__)"
fi
