#!/bin/sh
# Extract pure NMEA from an emailed gpsd error log.
# The output can be fed to gpsfake.
#
# This file is Copyright 2010 by the GPSD project
# SPDX-License-Identifier: BSD-2-clause
sed -n -e "/^> */s///" -e "/gpsd: <= GPS: /s///" -e '/^\$/p'


