= gpsd Client Example Code
Gary E. Miller <gem@rellim.com>
8 March 2021
:author: Gary E. Miller
:date: 8 March 2021
:description: Annotated gpsd client example code
:email: <gem@rellim.com>
:keywords: gpsd, example
:robots: index,follow
:sectlinks:
:source-highlighter: rouge
:toc: left

== ABSTRACT

This document supplies some code examples that show how to write
good *gpsd* clients.  It is an attempt to supplant the myriad bad
Stack Overflow examples of *gpsd* clients.

== EXAMPLE 1

A simple *gpsd* client that connects to the already running *gpsd* on
the _localhost_ running on the default port _2947_, using TCP.

This client prints the "mode" (Fix Type), "time" (Fix Time), "latitude"
and "longitude" if available.  This the Time and Position parts of
the acronym _TPV_.  Otherwise it prints nothing.

It runs fine as a normal user as it does not require any special
permissions.  Use "^C" to exit.

// The source highlighter and line numbers requires rouge to be installed
// Keep the line numbers in sync with the text.

[source,c,numbered]
----
// example  gpsd client
// compile this way:
//    gcc example.c -o example -lgps -lm
#include <gps.h>
#include <math.h>        // for isfinite()
#include <unistd.h>      // for sleep()

#define MODE_STR_NUM 4
static char *mode_str[MODE_STR_NUM] = {
    "n/a",
    "None",
    "2D",
    "3D"
};

int main(int argc, char *argv[])
{
    struct gps_data_t gps_data;

    if ( 0 != gps_open("localhost", "2947", &gps_data)) {
        printf("Open error.  Bye, bye\n");
        return 1;
    }

    (void)gps_stream(&gps_data, WATCH_ENABLE | WATCH_JSON, NULL);

    while (gps_waiting(&gps_data, 5000000)) {
        if (gps_read(&gps_data, NULL, 0) == -1) {
            printf("Read error.  Bye, bye\n");
            break;
        }
        if (MODE_SET != (MODE_SET & gps_data.set)) {
            // did not even get mode, nothing to see here
            continue;
        }
        if (0 > gps_data.fix.mode ||
            MODE_STR_NUM <= gps_data.fix.mode) {
            gps_data.fix.mode = 0;
        }
        printf("Fix mode: %s (%d) Time: ",
               mode_str[gps_data.fix.mode],
               gps_data.fix.mode);
        if (TIME_SET == (TIME_SET & gps_data.set)) {
            // not 32 bit safe
            printf("%ld.%09ld ", gps_data.fix.time.tv_sec,
                   gps_data.fix.time.tv_nsec);
        } else {
            puts("n/a ");
        }
        if (isfinite(gps_data.fix.latitude) &&
            isfinite( gps_data.fix.longitude)) {
            // Display data from the GPS receiver if valid.
            printf("Lat %.6f Lon %.6f\n",
                   gps_data.fix.latitude, gps_data.fix.longitude);
        }
    }

    /* When you are done... */
    (void)gps_stream(&gps_data, WATCH_DISABLE, NULL);
    (void)gps_close(&gps_data);
    return 0;
}
----

Line by line commentary:

2 to 4::  All you need to compile is *libgps*, and *gps.h*, installed on your
host.  Some systems require the libm be explicitly linked in.

5 to 6:: System includes to get isfinite() and sleep().

8 to 14::  An array of strings used to convert _fix.mode_ integer to a
nice "Fix Type" string.

16:: All we need is a simple main().  For clarity no options
handling is done.  Real programs will implement *-h*, *-V*,
*[server[;port[;device]]*, etc.

18:: All state variables are contained in *struct gps_data_a gps_data*
which is defined, and documented, in *gps.h*.  The _TPV_ data is
in _gps_data.fix_ which is a *struct gps_fix_t* also defined in *gps.h*.

20 to 23::  Connect to the already running *gpsd* on the _localhost_
running on the default port _2947_.  Or exit loudly.  There may be
significant delays opening the connection if *gpsd* is not running with
the "*-n" option.  See the *libgps* man page for details on *gps_open()*
and the other *gps_*()* function calls.

25:: Tell *gpsd* to send us reports using JSON.  See the *gpsd_json* an
page for details on the JSON messages.

27:: The main loop.  Wait, using *gps_waiting()* until *gpsd* data is
available, then run the body of the loop.  Exit if no data seen in 5
seconds.

28:: Read the waiting data using *gpsd_read()* into *gps_data*.  Exit
loudly on errors.  No telling, yet, what the data is.  It could be
from *TPV", *SKY*, *AIS*, or other message classes.

32 to 34:: Here is the part that most programmers miss.  Check that *TPV*
data was received.  The flag *MODE_SET* is set IFF a *TPV* JSON sentence
was received.  If no *MODE_SET* then do not bother to look at the rest
of the data in _gpsdata.fix_.

35 to 39:: Range check _gpsdata.fix.mode_ so we can use it as an index
into _mode_str_a Array overruns are bad.  New versions of *gpsd* often
extend the range of unenumerated types.

40 to 42:: Print the Fix mode as an integer, and a string.

45 to 49:: Print the _gps_data.fix.time_ as seconds and nano seconds
into the UNIX epoch, if we have it, else "n/a". _fix.time_ is a _struct
timespec_.  An explanation of _struct timepec_ can be found on the
*clock_gettime()* man page.
+
Just because we have a "valid" time does not mean it bears any relation
to UTC.  Many GPS/GNSS receivers output random time when they do not
have a fix.  Worse, some continue to do so for minutes after reporting
that they have a valid fix.

50 to 55:: Just because we have a "3D" fix does not mean we have
_latitude_ and _longitude_.  The receiver may not have sent that data
yet.  Conversely, some receivers will send them, without a fix, based on
some best guess.  This example prints them if we get them regardless of
fix "mode" or "status".
+
When *gpsd* does not know the value of a floating point variable, it
sets that variable to *NAN* (Not A Number).  So the example checks if
_latitude_ and _longitude_ are set by seeing if they are finite numbers by
using *isfinite()* from *libm*.  Do not use *isnan()*!
+
*IEEE 754* floating point math sometimes defies common logic.  A zero
divided by a one returns positive infinity (_+Inf_).  But isnan(_+Inf_)
returns _False_, because while _+Inf_ is one of many _NAN_, it is
special.  That is why the example uses *isfinite()*.

59 to 61::  When falling out of the loop, close the TCP connection nicely
and return success.  Mother always said to clean up after myself.

